### ISSUE TITLE
Google Play Protect warning

### ISSUE THREAD

**Issue by WeAreLiving1984** [hufrea/byedpi-neko#1]
![](https://github.com/user-attachments/assets/22552ef7-e506-44ac-b226-acf11915c7d9)

**Comment by bropines** [comment]
> ![](https://private-user-images.githubusercontent.com/177433675/354869206-22552ef7-e506-44ac-b226-acf11915c7d9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDA1ODcsIm5iZiI6MTcyMzgwMDI4NywicGF0aCI6Ii8xNzc0MzM2NzUvMzU0ODY5MjA2LTIyNTUyZWY3LWU1MDYtNDRhYy1iMjI2LWFjZjExOTE1YzdkOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwOTI0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWQ4YzY3ZDY2MDVhOTg1MmFjMjljY2Y4YmJjMjQ4NjA1MTg2Njk4YTAzMTZlYzhkOWJlZmE0YjhkNDk0ZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sEUiKASLMwoudykQxGPSA_PXOXk1f8vvH1VG-jSuv80)

Relax. Google complains about everything that is downloaded and signed with the developer's signature on github.

**Comment by SagePtr** [comment]
I noticed, it triggers with v0.12 byedpi binary, but doesn't trigger either with v0.11 and v0.13. So probably updating binary to v0.13 might solve this problem.

**Comment by SagePtr** [comment]
Tested building ByeDPI-Neko with ByeDPI v13.1, and it evades Google Play warning successfully. You can check my test build here: https://github.com/SagePtr/byedpi-neko/releases/tag/v0.2.1-pre1
